
// Code generated by go-mongodb-gen; DO NOT EDIT.

package mongodb

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
)

type LikecacheField[T any] interface {
	field.Field
	filter.ComparableFilter[T]
	updater.BaseUpdater[T]

	LikecacheFieldSubFields
}

type cacheField = LikecacheField[cache]

type LikecacheFieldSubFields interface {
	IDF() fields.StringField
	ValueF() fields.RawField
}

type likecacheField[T any] struct {
	fields.BaseField[T]
}

func NewLikecacheField[T any](name string) LikecacheField[T] {
	return &likecacheField[T]{
		*fields.NewBaseField[T](name),
	}
}

var NewcacheField = NewLikecacheField[cache]

func NewLikecacheFieldSubFields(name string) LikecacheFieldSubFields {
	return &likecacheField[any]{
		*fields.NewBaseField[any](name),
	}
}

var NewcacheFieldSubFields = NewLikecacheFieldSubFields

var cacheColl = struct{
	DefaultName string
	LikecacheFieldSubFields
}{ "cache", NewcacheFieldSubFields("")}

func (s *likecacheField[T]) IDF() fields.StringField {
	return fields.NewStringField(fields.SubField(s.FullName(), "_id"))
}

func (s *likecacheField[T]) ValueF() fields.RawField {
	return fields.NewRawField(fields.SubField(s.FullName(), "value"))
}
