
// Code generated by go-mongodb-gen; DO NOT EDIT.

package mongodb

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
)

type LikestreamField[T any] interface {
	field.Field
	filter.ComparableFilter[T]
	updater.BaseUpdater[T]

	LikestreamFieldSubFields
}

type streamField = LikestreamField[stream]

type LikestreamFieldSubFields interface {
	TokenF() fields.BinaryField
	ValueF() fields.RawField
	SeqF() fields.Uint64Field
}

type likestreamField[T any] struct {
	fields.BaseField[T]
}

func NewLikestreamField[T any](name string) LikestreamField[T] {
	return &likestreamField[T]{
		*fields.NewBaseField[T](name),
	}
}

var NewstreamField = NewLikestreamField[stream]

func NewLikestreamFieldSubFields(name string) LikestreamFieldSubFields {
	return &likestreamField[any]{
		*fields.NewBaseField[any](name),
	}
}

var NewstreamFieldSubFields = NewLikestreamFieldSubFields

var streamColl = struct{
	DefaultName string
	LikestreamFieldSubFields
}{ "stream", NewstreamFieldSubFields("")}

func (s *likestreamField[T]) TokenF() fields.BinaryField {
	return fields.NewBinaryField(fields.SubField(s.FullName(), "_id"))
}

func (s *likestreamField[T]) ValueF() fields.RawField {
	return fields.NewRawField(fields.SubField(s.FullName(), "value"))
}

func (s *likestreamField[T]) SeqF() fields.Uint64Field {
	return fields.NewUint64Field(fields.SubField(s.FullName(), "seq"))
}
